[package]
name = "space_invaders"
version = "0.1.0"
authors = ["AntonHermann <antonoehler@gmx.de>"]

[dependencies]
clap = "2"
log = "0.4"
loggerv = "0.7"
failure = "*"
failure_derive = "*"
termion = "1.5.1"
specs = "0.10.0"
